//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrichmentClassRegistration
    {
        public int EnrichmentClassRegistrationId { get; set; }
        public int StudentId { get; set; }
        public int SemesterId { get; set; }
        public Nullable<int> EnrichmentClassId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public bool ActiveFlag { get; set; }
        public System.DateTime CreateTimeStemp { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime UpdateTimeStemp { get; set; }
        public string UpdateUserId { get; set; }
    
        public virtual EnrichmentClass EnrichmentClass { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
