//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrichmentClass
    {
        public EnrichmentClass()
        {
            this.EnrichmentClassRegistrations = new HashSet<EnrichmentClassRegistration>();
            this.EnrichmentClassTeacherAssignments = new HashSet<EnrichmentClassTeacherAssignment>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public decimal Price1 { get; set; }
        public string Price1Description { get; set; }
        public decimal Price2 { get; set; }
        public string Price2Descrioption { get; set; }
        public bool ActiveFlg { get; set; }
        public System.DateTime CreateTimeStemp { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime UpdateTimeStemp { get; set; }
        public string UpdateUserId { get; set; }
    
        public virtual ICollection<EnrichmentClassRegistration> EnrichmentClassRegistrations { get; set; }
        public virtual ICollection<EnrichmentClassTeacherAssignment> EnrichmentClassTeacherAssignments { get; set; }
    }
}
