//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrichmentClassTeacherAssignment
    {
        public int EnrichmentClassTeacherAssignmentId { get; set; }
        public int EnrichmentClassId { get; set; }
        public int TeacherId { get; set; }
        public int SemesterId { get; set; }
        public System.DateTime upsrt_dttm { get; set; }
        public string upsrt_user { get; set; }
    
        public virtual EnrichmentClass EnrichmentClass { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
