//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public int EventId { get; set; }
        public string ImagePath { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreateTimeStamp { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public string ThumbNailPath { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
