//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int ParentId { get; set; }
        public int SemesterId { get; set; }
        public bool ActiveFlg { get; set; }
        public string Comment { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
