//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Students = new HashSet<Student>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ParentsId { get; set; }
        public string UserId { get; set; }
        public string Parent1Firstname { get; set; }
        public string Parent1LastName { get; set; }
        public string Parent2Firstname { get; set; }
        public string Parent2Lastname { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public System.DateTime CreateTimeStemp { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime UpdateTimeStemp { get; set; }
        public string UpdateUserId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
