//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Stuffs = new HashSet<Stuff>();
        }
    
        public int PositionID { get; set; }
        public int PositionTypeId { get; set; }
        public string PositionName { get; set; }
        public bool IsExclusive { get; set; }
        public bool IsActive { get; set; }
        public string upsrt_user { get; set; }
        public System.DateTime upsrt_dttm { get; set; }
    
        public virtual PositionType PositionType { get; set; }
        public virtual ICollection<Stuff> Stuffs { get; set; }
    }
}
