//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionType
    {
        public PositionType()
        {
            this.Positions = new HashSet<Position>();
        }
    
        public int PositionTypeId { get; set; }
        public string PositionTypeName { get; set; }
        public System.DateTime upsrt_dttm { get; set; }
        public string upsrt_user { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Position> Positions { get; set; }
    }
}
