//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.ClassRegistrations = new HashSet<ClassRegistration>();
            this.ClassTeacherAssignments = new HashSet<ClassTeacherAssignment>();
            this.EnrichmentClassRegistrations = new HashSet<EnrichmentClassRegistration>();
            this.Invoices = new HashSet<Invoice>();
            this.Transactions = new HashSet<Transaction>();
            this.EnrichmentClassTeacherAssignments = new HashSet<EnrichmentClassTeacherAssignment>();
        }
    
        public int SemesterID { get; set; }
        public int SemesterYear { get; set; }
        public string SemesterSeason { get; set; }
        public System.DateTime RegisterStartDate { get; set; }
        public System.DateTime RegisterEndDate { get; set; }
        public decimal Price1 { get; set; }
        public string Price1Description { get; set; }
        public decimal Price2 { get; set; }
        public string Price2Description { get; set; }
        public decimal Price3 { get; set; }
        public string Price3Description { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public string Price4Description { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public string Price5Description { get; set; }
        public bool ActiveFlg { get; set; }
        public System.DateTime CreateTimeStemp { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime UpdateTimeStemp { get; set; }
        public string UpdateUserId { get; set; }
        public decimal RegistrationFeeBeforeEndDate { get; set; }
        public decimal RegistrationFeeAfterEndDate { get; set; }
        public decimal VolunteerDeposit { get; set; }
        public decimal BookCharge { get; set; }
    
        public virtual ICollection<ClassRegistration> ClassRegistrations { get; set; }
        public virtual ICollection<ClassTeacherAssignment> ClassTeacherAssignments { get; set; }
        public virtual ICollection<EnrichmentClassRegistration> EnrichmentClassRegistrations { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<EnrichmentClassTeacherAssignment> EnrichmentClassTeacherAssignments { get; set; }
    }
}
