//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.ClassRegistrations = new HashSet<ClassRegistration>();
            this.EnrichmentClassRegistrations = new HashSet<EnrichmentClassRegistration>();
        }
    
        public int StudentId { get; set; }
        public int ParentsId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string MiddleInitial { get; set; }
        public string Chinesename { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<byte> Grade { get; set; }
        public string Class { get; set; }
        public System.DateTime CreateTimeStemp { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime UpdateTimeStemp { get; set; }
        public string UpdateUserId { get; set; }
        public bool RegisterClass { get; set; }
        public string EnrichmentClass { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<ClassRegistration> ClassRegistrations { get; set; }
        public virtual ICollection<EnrichmentClassRegistration> EnrichmentClassRegistrations { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
