//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.ClassTeacherAssignments = new HashSet<ClassTeacherAssignment>();
            this.EnrichmentClassTeacherAssignments = new HashSet<EnrichmentClassTeacherAssignment>();
        }
    
        public int TeacherId { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime upsrt_dttm { get; set; }
        public string upsrt_user { get; set; }
        public string ThumbNailPath { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ClassTeacherAssignment> ClassTeacherAssignments { get; set; }
        public virtual ICollection<EnrichmentClassTeacherAssignment> EnrichmentClassTeacherAssignments { get; set; }
    }
}
