//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_StudentClassDetails
    {
        public int ParentsId { get; set; }
        public string Parent1Firstname { get; set; }
        public string Parent1LastName { get; set; }
        public int StudentId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Classname { get; set; }
        public decimal Amount { get; set; }
    }
}
