//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoId { get; set; }
        public int EventId { get; set; }
        public string VideoLink { get; set; }
        public Nullable<System.DateTime> upsrt_dttm { get; set; }
        public string upsrt_user { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
